services:
  nextn-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextn-container
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - PORT=9002
      - HOSTNAME=0.0.0.0
      # - SUPABASE_URL=...
      # - SUPABASE_ANON_KEY=...
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - nextn-network

networks:
  nextn-network:
    driver: bridge