services:
  nextn-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextn-container
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - PORT=9002
      - HOSTNAME=https://powerup.marivibarrios.com/login   # Cambia aquí la URL/IP que desees
      # - SUPABASE_URL=...
      # - SUPABASE_ANON_KEY=...
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - nextn-network

  # Opcional: Si necesitas una base de datos PostgreSQL para desarrollo
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: nextn-postgres
  #   environment:
  #     POSTGRES_DB: nextn
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - nextn-network

networks:
  nextn-network:
    driver: bridge

# volumes:
#   postgres_data: